# Generated by Django 3.0.6 on 2020-05-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('gear', models.CharField(max_length=50)),
                ('chassis', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('horse_power', models.PositiveIntegerField()),
                ('features', models.TextField()),
                ('capacity', models.CharField(max_length=50)),
                ('fuel', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('color', models.CharField(max_length=200)),
                ('chassis_number', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('store_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
